name: ESET Mass Key Generator

on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Mail provider'
        required: true
        type: choice
        options:
          - 1secmail
          - guerrillamail
          - developermail
          - mailticking
          - fakemail
          - inboxes
          - incognitomail
          - emailfake
        default: emailfake
      key_count:
        description: 'Number of keys to generate (1-10)'
        required: true
        type: choice
        options:
           - 1
           - 2
           - 3
           - 4
           - 5
           - 6
           - 7
           - 8
           - 9
           - 10
        default: '1'
      user_chat_id:
        description: 'Telegram chat ID'
        required: true

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone ESET-KeyGen
        shell: pwsh
        run: |
          git clone -b main https://github.com/XHub157/ESET-KeyGen
          cd ESET-KeyGen
          Remove-Item -Path .\*KEYS.txt -ErrorAction SilentlyContinue

      - name: Setup environment
        shell: pwsh
        run: |
          cd ESET-KeyGen
          python -m venv venv
          .\venv\Scripts\pip install -r requirements.txt

      - name: Generate multiple keys
        id: generate
        shell: pwsh
        run: |
          cd ESET-KeyGen
          $allKeys = @()
          $keyCount = ${{ inputs.key_count }}
          
          Write-Output "Начинаем генерацию $keyCount ключей..."
          
          for ($i = 1; $i -le $keyCount; $i++) {
              Write-Output "Генерация ключа #$i из $keyCount"
              
              $outputFile = ".\output_$i.txt"
              .\venv\Scripts\python main.py --auto-detect-browser --key `
                --email-api "${{ inputs.mail }}" `
                --skip-update-check --no-logo `
                --disable-progress-bar --disable-logging *>&1 > $outputFile
              
              $lastLines = Get-Content $outputFile | Select-Object -Last 30
              $content = $lastLines -join "`n"
              
              $patterns = @(
                  'License Key: ([A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4})',
                  'License Key: ([A-Z0-9]{15})',
                  'Key: ([A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4})'
              )
              
              $licenseKey = $null
              foreach ($pattern in $patterns) {
                  $match = [regex]::Match($content, $pattern)
                  if ($match.Success) {
                      $licenseKey = $match.Groups[1].Value
                      break
                  }
              }
              
              if ($licenseKey) {
                  Write-Output "Найден ключ #$i : $licenseKey"
                  $allKeys += $licenseKey
              } else {
                  Write-Output "::warning::Ключ #$i не найден в выводе, пропускаем..."
                  continue
              }
              
              Start-Sleep -Seconds 2
          }
          
          if ($allKeys.Count -gt 0) {
              $keysJson = $allKeys | ConvertTo-Json -Compress
              echo "ALL_KEYS=$keysJson" >> $env:GITHUB_ENV
              echo "TOTAL_KEYS=$($allKeys.Count)" >> $env:GITHUB_ENV
              Write-Output "Успешно сгенерировано ключей: $($allKeys.Count) из $keyCount"
          } else {
              echo "::error::Не удалось сгенерировать ни одного ключа"
              exit 1
          }

      - name: Send keys to Telegram
        if: success()
        shell: pwsh
        run: |
          $keysArray = $env:ALL_KEYS | ConvertFrom-Json
          $totalKeys = $env:TOTAL_KEYS
          
          if ($totalKeys -eq ${{ inputs.key_count }}) {
              $messageText = "✅ Успешно сгенерировано $totalKeys ключей ESET:`n`n"
          } else {
              $messageText = "⚠️ Сгенерировано $totalKeys из ${{ inputs.key_count }} ключей ESET:`n`n"
          }
          
          foreach ($key in $keysArray) {
              $messageText += "`<code>$key</code>`n"
          }
          
          $messageText += "`n📅Сгенерировано $(Get-Date -Format 'dd.MM.yyyy')`n@EsetgenBot"
          
          $url = "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
          
          $replyMarkup = '{
            "inline_keyboard": [
              [
                {
                  "text": "🙏 Сказать спасибо",
                  "url": "https://t.me/+wnr6bruMFitmM2Zi"
                }
              ]
            ]
          }'
          
          $body = @{
              chat_id = "${{ inputs.user_chat_id }}"
              text = $messageText
              parse_mode = "HTML"
              reply_markup = $replyMarkup
          }
          
          try {
              $response = Invoke-RestMethod -Uri $url -Method Post -Body $body -ErrorAction Stop
              Write-Output "Сообщение с $totalKeys ключами отправлено!"
          } catch {
              Write-Output "::error::Ошибка отправки: $_"
              $keysArray | ForEach-Object { Write-Output "Ключ: $_" }
              exit 1
          }

      - name: Cleanup
        if: always()
        shell: pwsh
        run: |
          cd ESET-KeyGen
          Remove-Item -Path .\output_*.txt -ErrorAction SilentlyContinue
